-- MySQL Script generated by MySQL Workbench
-- Thu Feb 12 17:07:05 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sistema_f1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Sistema_f1` ;

-- -----------------------------------------------------
-- Schema Sistema_f1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sistema_f1` DEFAULT CHARACTER SET utf8 ;
USE `Sistema_f1` ;

-- -----------------------------------------------------
-- Table `Sistema_f1`.`equipes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_f1`.`equipes` ;

CREATE TABLE IF NOT EXISTS `Sistema_f1`.`equipes` (
  `idequipes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `cor` VARCHAR(255) NULL DEFAULT 'None',
  PRIMARY KEY (`idequipes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_f1`.`pilotos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_f1`.`pilotos` ;

CREATE TABLE IF NOT EXISTS `Sistema_f1`.`pilotos` (
  `idpilotos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `idade` INT NOT NULL,
  `pontos` INT NULL DEFAULT 0,
  `vitorias` INT NULL DEFAULT 0,
  `podios` INT NULL DEFAULT 0,
  `idequipe` INT NOT NULL,
  PRIMARY KEY (`idpilotos`, `idequipe`),
  INDEX `fk_pilotos_equipes_idx` (`idequipe` ASC) VISIBLE,
  CONSTRAINT `fk_pilotos_equipes`
    FOREIGN KEY (`idequipe`)
    REFERENCES `Sistema_f1`.`equipes` (`idequipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_f1`.`pistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_f1`.`pistas` ;

CREATE TABLE IF NOT EXISTS `Sistema_f1`.`pistas` (
  `idpistas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `tamanho` INT NOT NULL,
  PRIMARY KEY (`idpistas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_f1`.`corridas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_f1`.`corridas` ;

CREATE TABLE IF NOT EXISTS `Sistema_f1`.`corridas` (
  `idcorridas` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `duracao` INT NOT NULL,
  `idpista` INT NOT NULL,
  PRIMARY KEY (`idcorridas`, `idpista`),
  INDEX `fk_corridas_pistas1_idx` (`idpista` ASC) VISIBLE,
  CONSTRAINT `fk_corridas_pistas1`
    FOREIGN KEY (`idpista`)
    REFERENCES `Sistema_f1`.`pistas` (`idpistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sistema_f1`.`resultado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sistema_f1`.`resultado` ;

CREATE TABLE IF NOT EXISTS `Sistema_f1`.`resultado` (
  `idresultado` INT NOT NULL AUTO_INCREMENT,
  `posicao` INT NOT NULL,
  `idcorrida` INT NOT NULL,
  `idpiloto` INT NOT NULL,
  `idequipe` INT NOT NULL,
  `pontos` INT NOT NULL,
  PRIMARY KEY (`idresultado`, `idcorrida`, `idpiloto`, `idequipe`),
  INDEX `fk_resultado_corridas1_idx` (`idcorrida` ASC) VISIBLE,
  INDEX `fk_resultado_pilotos1_idx` (`idpiloto` ASC) VISIBLE,
  INDEX `fk_resultado_equipes1_idx` (`idequipe` ASC) VISIBLE,
  CONSTRAINT `fk_resultado_corridas1`
    FOREIGN KEY (`idcorrida`)
    REFERENCES `Sistema_f1`.`corridas` (`idcorridas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultado_pilotos1`
    FOREIGN KEY (`idpiloto`)
    REFERENCES `Sistema_f1`.`pilotos` (`idpilotos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resultado_equipes1`
    FOREIGN KEY (`idequipe`)
    REFERENCES `Sistema_f1`.`equipes` (`idequipes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
